"""Every number the classifier compares against, and where each one was measured.

A threshold whose ``calibrated_on`` is empty fails
``test/test_spatial3d_a_classifier_verdict_carries_its_evidence.py``. That is the entire
mechanism, and it exists because a plausible-looking constant is the easiest thing in this
package to get wrong and the hardest to notice: it produces confident verdicts forever.

The measurements live in ``docs/design/spatial_3d_thresholds.csv``, regenerated by
``python -m spatialomicsgym.spatial3d._calibrate``. Two of them are worth reading before trusting
any number here.

**Real serial sections are far less self-similar than intuition suggests.** Over the 142
properly-spaced adjacent pairs of Zhuang-ABCA-1 -- a stack the Allen Institute had already placed
in a shared coordinate frame, so a known class A -- the median outline IoU is **0.37** and the
maximum over every pair is **0.465**. A class-A gate of "IoU above 0.70", which is what the shape
of the question suggests, classifies the entire atlas as misaligned. Adjacent coronal sections
100 micrometres apart genuinely have different outlines, because the brain changes shape along
the axis being stacked. IoU is therefore reported and never gated on.

**The four Zhuang sections at z = 0 are excluded from every number here.** The provider clamps
negative anterior estimates to zero, so those sections occupy one plane and their ordering is
invented; their pairs measure a centroid offset of 0.20 and a local shift of 0.08 purely because
they were sorted. Calibrating on them would move every class-A threshold far enough to admit real
misalignment. The diagnosis reports coincident-z groups rather than silently ordering them.
"""

from __future__ import annotations

from dataclasses import dataclass

CALIBRATION_TABLE = "docs/design/spatial_3d_thresholds.csv"


@dataclass(frozen=True)
class Threshold:
    """One number, and the evidence that it is the right number."""

    name: str
    value: float
    units: str
    calibrated_on: str
    n_observations: int
    rationale: str
    calibration_table: str = CALIBRATION_TABLE

    def __float__(self) -> float:
        return float(self.value)

    def cite(self, observed: float) -> str:
        """The sentence a report prints beside a measurement."""
        return f"{observed:.4g} against {self.value:g} ({self.units}), from {self.calibrated_on}"


#: Centroid offset above which a pair is not "already aligned". The strongest single signal and
#: the only one with a clean gap between the real class-A stack and a realistic misalignment.
T_A_CENTROID = Threshold(
    name="T_A_centroid",
    value=0.10,
    units="fraction of the pooled robust bbox diagonal",
    calibrated_on="Zhuang-ABCA-1, 142 adjacent pairs, p95 = 0.0851, max = 0.1960",
    n_observations=142,
    rationale=(
        "Set just above the 95th percentile of a known class-A stack, so ordinary anatomical "
        "drift between adjacent sections does not read as misalignment. The synthetic class-B "
        "fixture, whose translations are at the scale of real unregistered stage coordinates, has "
        "a minimum of 0.3438 -- a clean gap, with nothing measured in between."
    ),
)

#: Local-shift dispersion above which one global similarity transform does not explain the pair.
T_A_LOCAL_SHIFT = Threshold(
    name="T_A_local_shift",
    value=0.055,
    units="fraction of the pooled robust bbox diagonal",
    calibrated_on="Zhuang-ABCA-1, 142 adjacent pairs, p95 = 0.0338, max = 0.0535",
    n_observations=142,
    rationale=(
        "Set at the maximum observed on the real class-A stack, so no correctly aligned pair in "
        "142 trips it. The synthetic class-C fixture measures a median of 0.0658 above it."
    ),
)

#: Containment below which two sections share too little tissue to be called aligned.
T_A_CONTAINMENT = Threshold(
    name="T_A_containment",
    value=0.35,
    units="fraction, |A and B| / min(|A|, |B|) over occupancy bins",
    calibrated_on="Zhuang-ABCA-1, 142 adjacent pairs, p05 = 0.4281, min = 0.3885",
    n_observations=142,
    rationale=(
        "Set below the minimum observed on the real class-A stack. Containment rather than IoU, "
        "because IoU on real adjacent sections is only 0.37 and cannot be gated on; containment "
        "asks the weaker and answerable question of whether the smaller section is inside the "
        "larger one."
    ),
)

#: Local-shift dispersion at which a pair is positively called non-rigid.
T_C_LOCAL_SHIFT = Threshold(
    name="T_C_local_shift",
    value=0.055,
    units="fraction of the pooled robust bbox diagonal",
    calibrated_on="Zhuang-ABCA-1 max = 0.0535; class-C fixture median = 0.0658",
    n_observations=146,
    rationale=(
        "Deliberately equal to T_A_local_shift: there is no measured gap between the worst real "
        "class-A pair and the best synthetic class-C pair, so inventing one would be a fiction. "
        "A pair between the two is not silently split -- the stack rule below needs a fraction of "
        "pairs to agree before it calls the stack non-rigid."
    ),
)

#: Aspect change at which a pair is positively called non-rigid. Anisotropic stretch is the
#: deformation a similarity transform provably cannot undo.
T_C_ASPECT = Threshold(
    name="T_C_aspect",
    value=0.80,
    units="absolute log2 ratio of bounding-box aspect ratios",
    calibrated_on="Zhuang-ABCA-1 p95 = 0.3695, max = 0.7785; class-C fixture median = 0.8380",
    n_observations=146,
    rationale=(
        "Set just above the maximum over 142 real class-A pairs, so anatomy changing along the "
        "stacking axis never trips it. Real sections do change aspect -- the p95 is 0.37 -- which "
        "is why this cannot be set anywhere near zero."
    ),
)

#: Containment minus recentred IoU, above which the pair looks like partial overlap rather than
#: displacement: one section largely inside the other, but covering much less of it.
T_C_PARTIAL = Threshold(
    name="T_C_partial",
    value=0.30,
    units="difference of two fractions",
    calibrated_on=(
        "Zhuang-ABCA-1 142 pairs, p95 of (containment - iou_recentred) = 0.2501, max = 0.2972; "
        "class-C fixture max = 0.3107"
    ),
    n_observations=142,
    rationale=(
        "Above the maximum over the real class-A stack, so no correctly aligned pair trips it. "
        "This is the weakest of the three class-C criteria and is recorded as such: only one of "
        "the four class-C fixture pairs exceeds it, because the gap between the worst real "
        "class-A pair (0.2972) and the best synthetic partial-overlap pair (0.3107) is 0.0135. "
        "It is a supporting criterion, never a sole trigger -- which is what the stack-level "
        "fraction rule enforces."
    ),
)

#: Expression-agreement gap below which the pair carries no biological evidence of continuity.
T_BIO_GAP = Threshold(
    name="T_bio_gap",
    value=0.05,
    units="difference of two Spearman rho",
    calibrated_on="the rotated-90-degree null of the same pipeline, on the serial-section fixtures",
    n_observations=12,
    rationale=(
        "The statistic is a difference against a deliberately wrong registration, so zero means "
        "'matching these sections tells us nothing a wrong match would not'. The floor is set "
        "just above zero rather than at a correlation value, because the correlation itself is "
        "not comparable between tissues and the gap is."
    ),
)

#: Fraction of adjacent pairs that must be class A for the stack to be class A.
STACK_A_FRACTION = Threshold(
    name="stack_A_fraction",
    value=0.90,
    units="fraction of adjacent pairs",
    calibrated_on="Zhuang-ABCA-1: 142 pairs, of which the number exceeding T_A_centroid is small",
    n_observations=142,
    rationale=(
        "A real stack has a bad pair or two -- a fractured section, a fold -- without being "
        "misaligned as a whole. One tenth is the tolerance the Zhuang atlas needs and no more."
    ),
)

#: Fraction of pairs that must be positively non-rigid for the stack to be class C.
STACK_C_FRACTION = Threshold(
    name="stack_C_fraction",
    value=0.10,
    units="fraction of adjacent pairs",
    calibrated_on="Zhuang-ABCA-1: 0 of 142 pairs trip either class-C criterion",
    n_observations=142,
    rationale=(
        "Low, because a deformation in one section is still a deformation and rigid alignment "
        "will not fix it. It is safe to set low precisely because no pair of the real class-A "
        "stack trips a class-C criterion at all."
    ),
)

#: Fraction of pairs that may be unmeasurable before the stack verdict itself is 'unknown'.
STACK_UNKNOWN_FRACTION = Threshold(
    name="stack_unknown_fraction",
    value=0.20,
    units="fraction of adjacent pairs",
    calibrated_on="Zhuang-ABCA-1: every one of 142 pairs yielded all gated metrics",
    n_observations=142,
    rationale=(
        "A verdict drawn from four fifths of the pairs is still a verdict; one drawn from half is "
        "a guess with a label. Note that the principal-axis angle is refused on 82 of the 142 "
        "real pairs, which is why no class gate depends on it."
    ),
)

ALL: tuple[Threshold, ...] = (
    T_A_CENTROID,
    T_A_LOCAL_SHIFT,
    T_A_CONTAINMENT,
    T_C_LOCAL_SHIFT,
    T_C_ASPECT,
    T_C_PARTIAL,
    T_BIO_GAP,
    STACK_A_FRACTION,
    STACK_C_FRACTION,
    STACK_UNKNOWN_FRACTION,
)
