"""Sphinx extension: generate the tool-catalogue pages at build time.

The pages under ``docs/tools/`` are **generated**, never edited by hand, so the documentation can
not drift from the platform it describes. Three tracked sources feed them:

* ``install/recipes/tool_specs/<key>.yaml`` — one spec per MCP server: its portal and worker files,
  the conda env it runs in, whether it wants a GPU, and the analysis *category* of each function.
* ``agent/MCP_server/mcp_config.yaml`` — the canonical MCP config: each server's description and,
  for each function, its description and parameters (type, required, default, description).
* ``agent/spatialomicsgym/tool/tool_description/<subject>.py`` — the in-process research tools
  (plain Python literals; they are read with :func:`ast.literal_eval`, never imported or executed).

This is the same material ``python -m sog_install.tools_catalog --write`` renders into
``agent/tools/CATALOG.md``; here it is split into one page per category, with the function
parameters that the one-line catalogue leaves out.

The extension runs on Sphinx's ``builder-inited`` event, before any source file is read, and
writes Markdown (MyST) files. It needs only the standard library and PyYAML. Run it directly
(``python docs/_ext/sog_tool_catalogue.py``) to regenerate the pages without a Sphinx build.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from sphinx.application import Sphinx

DOCS_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = DOCS_DIR.parent
SPECS_DIR = REPO_ROOT / "install" / "recipes" / "tool_specs"
CONFIG_PATH = REPO_ROOT / "agent" / "MCP_server" / "mcp_config.yaml"
TOOL_DESCRIPTIONS_DIR = REPO_ROOT / "agent" / "spatialomicsgym" / "tool" / "tool_description"
OUTPUT_DIR = DOCS_DIR / "tools"

GENERATED_NOTE = (
    "% GENERATED by docs/_ext/sog_tool_catalogue.py from install/recipes/tool_specs/,\n"
    "% agent/MCP_server/mcp_config.yaml and agent/spatialomicsgym/tool/tool_description/.\n"
    "% Do not edit this file: edit the specs or the config instead."
)

DATA_REQUIREMENTS_MARKER = "[DATA REQUIREMENTS]"
UNCATEGORISED = "uncategorised"

# Display order, title and blurb of each skill category. Any category found in the specs that is not
# listed here is appended after these, titled from its key.
CATEGORIES: dict[str, tuple[str, str]] = {
    "spatial_clustering": (
        "Spatial clustering",
        "Spatial domain identification: partition a slide into tissue domains from gene expression and "
        "spatial coordinates.",
    ),
    "deconvolution": (
        "Deconvolution",
        "Cell-type deconvolution and single-cell-to-spot mapping against a single-cell reference, plus "
        "reference-free alternatives.",
    ),
    "svg_detection": (
        "Spatially variable genes",
        "Detect genes whose expression varies across the tissue, and group them into spatial modules.",
    ),
    "cell_segmentation": (
        "Cell segmentation",
        "Segment cells and nuclei in microscopy and imaging-based spatial data.",
    ),
    "spatial_alignment": (
        "Alignment and 3D",
        "Register serial sections, map cells between slices and reconstruct 3D tissue stacks.",
    ),
    "spatial_communication": (
        "Cell–cell communication",
        "Infer ligand–receptor signalling and neighbourhood interactions from spatial data.",
    ),
    "spatial_analysis": (
        "General spatial analysis",
        "Quality control, spatial statistics, integration, imputation, pathway activity and publication "
        "figures.",
    ),
    "data_conversion": (
        "Data conversion",
        "Convert between h5ad, CSV and Seurat RDS.",
    ),
}


# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #
@dataclass
class Function:
    name: str
    category: str = UNCATEGORISED
    description: str = ""
    parameters: list[dict[str, Any]] = field(default_factory=list)
    wired: bool = True  # False: in the spec, but absent from the canonical config


@dataclass
class Server:
    key: str
    portal: str = ""
    worker: str = ""
    worker_kind: str = ""
    env: str = ""
    builds_env: bool = True
    gpu: bool = False
    est_gb: float | None = None
    description: str = ""
    enabled: bool = True
    functions: list[Function] = field(default_factory=list)

    @property
    def primary_category(self) -> str:
        return self.functions[0].category if self.functions else UNCATEGORISED

    @property
    def categories(self) -> list[str]:
        seen: list[str] = []
        for fn in self.functions:
            if fn.category not in seen:
                seen.append(fn.category)
        return seen


@dataclass
class InProcessTool:
    name: str
    module: str
    description: str
    required: list[dict[str, Any]]
    optional: list[dict[str, Any]]


# --------------------------------------------------------------------------- #
# Reading
# --------------------------------------------------------------------------- #
def _env_of_interpreter(path: str) -> str:
    """``.../envs/<name>/bin/python`` -> ``<name>``; a base ``bin/`` -> ``base``; otherwise ``""``."""
    parts = Path(str(path)).parts
    if "envs" in parts:
        i = parts.index("envs")
        if i + 1 < len(parts):
            return parts[i + 1]
    return "base" if "bin" in parts else ""


def _interpreter_env(env_vars: dict[str, Any]) -> str:
    for var in sorted(env_vars):
        if var.endswith(("_PYTHON", "_RSCRIPT")):
            name = _env_of_interpreter(env_vars[var])
            if name:
                return name
    return ""


def read_servers(specs_dir: Path = SPECS_DIR, config_path: Path = CONFIG_PATH) -> dict[str, Server]:
    """Merge the tool specs with the canonical MCP config into one :class:`Server` per key."""
    config = (yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}).get("mcp_servers") or {}
    specs: dict[str, dict[str, Any]] = {}
    for spec_file in sorted(specs_dir.glob("*.yaml")):
        spec = yaml.safe_load(spec_file.read_text(encoding="utf-8")) or {}
        if not isinstance(spec, dict) or not spec.get("server_key"):
            continue  # index.yaml and the like are not server specs
        specs[spec["server_key"]] = spec

    servers: dict[str, Server] = {}
    for key in sorted(set(specs) | set(config)):
        spec = specs.get(key, {})
        entry = config.get(key) or {}
        server = Server(key=key)

        # Files, env and hardware come from the spec; the config is the fallback.
        server.portal = spec.get("server_file") or next(
            (Path(str(a)).name for a in entry.get("command") or [] if str(a).endswith(".py")), ""
        )
        server.worker = spec.get("worker_file") or next(
            (Path(str(v)).name for k, v in sorted((entry.get("env") or {}).items()) if k.endswith("_WORKER") and v),
            "",
        )
        kind = str(spec.get("worker_kind") or "").lower()
        server.worker_kind = "r" if kind.startswith("r") or server.worker.endswith(".R") else "python"
        if spec.get("source_env"):
            server.env = str(spec["source_env"])
            server.builds_env = True
        else:
            server.env = _interpreter_env(spec.get("override_vars") or entry.get("env") or {})
            server.builds_env = False
        server.gpu = bool(spec.get("gpu", False))
        server.est_gb = spec.get("est_gb")
        server.description = " ".join(str(entry.get("description") or "").split())
        server.enabled = entry.get("enabled", True) is not False

        categories = {
            f["name"]: f.get("category") or UNCATEGORISED for f in spec.get("functions") or [] if f.get("name")
        }
        for tool in entry.get("tools") or []:
            name = tool.get("spatialomicsgym_name")
            if not name:
                continue
            params = []
            for pname, pinfo in (tool.get("parameters") or {}).items():
                pinfo = pinfo or {}
                params.append(
                    {
                        "name": pname,
                        "type": pinfo.get("type", ""),
                        "required": bool(pinfo.get("required", False)),
                        "default": pinfo.get("default"),
                        "description": " ".join(str(pinfo.get("description") or "").split()),
                    }
                )
            server.functions.append(
                Function(
                    name=name,
                    category=categories.get(name, UNCATEGORISED),
                    description=" ".join(str(tool.get("description") or "").split()),
                    parameters=params,
                )
            )
        # A function the spec knows but the config does not wire still gets a row, without parameters.
        for name, category in categories.items():
            if all(fn.name != name for fn in server.functions):
                server.functions.append(Function(name=name, category=category, wired=False))
        servers[key] = server
    return servers


def read_in_process_tools(descriptions_dir: Path = TOOL_DESCRIPTIONS_DIR) -> dict[str, list[InProcessTool]]:
    """Read the ``description = [...]`` literal of every ``tool_description/<subject>.py`` without importing it."""
    by_module: dict[str, list[InProcessTool]] = {}
    for py in sorted(descriptions_dir.glob("*.py")):
        if py.name.startswith("_"):
            continue
        tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
        entries: list[Any] = []
        for node in tree.body:
            if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "description" for t in node.targets):
                try:
                    entries = ast.literal_eval(node.value)
                except (ValueError, SyntaxError):
                    entries = []
                break
        tools = [
            InProcessTool(
                name=str(e.get("name", "")),
                module=py.stem,
                description=" ".join(str(e.get("description") or "").split()),
                required=list(e.get("required_parameters") or []),
                optional=list(e.get("optional_parameters") or []),
            )
            for e in entries
            if isinstance(e, dict) and e.get("name")
        ]
        if tools:
            by_module[py.stem] = tools
    return by_module


# --------------------------------------------------------------------------- #
# Markdown helpers
# --------------------------------------------------------------------------- #
_ESCAPES = str.maketrans({"*": r"\*", "_": r"\_", "[": r"\[", "]": r"\]", "<": "&lt;", ">": "&gt;", "|": r"\|"})


def md_text(text: str, *, in_table: bool = False) -> str:
    """Escape prose for MyST while keeping balanced backtick code spans intact."""
    text = " ".join(str(text or "").split())
    if text.count("`") % 2:
        text = text.replace("`", "")
    out: list[str] = []
    for i, chunk in enumerate(text.split("`")):
        if i % 2:  # inside a code span: only the table delimiter needs care
            out.append("`" + (chunk.replace("|", "\\|") if in_table else chunk) + "`")
        else:
            escaped = chunk.translate(_ESCAPES)
            if not in_table:
                escaped = escaped.replace("\\|", "|")
            out.append(escaped)
    return "".join(out)


def md_code(value: Any, *, in_table: bool = False) -> str:
    """A code span; inside a table the cell delimiter is escaped (markdown-it drops the backslash again)."""
    text = str(value).replace("`", "")
    if in_table:
        text = text.replace("|", "\\|")
    return f"`{text}`" if text else ""


def md_default(param: dict[str, Any]) -> str:
    """The default of a parameter as a table cell: ``—`` when there is none."""
    default = param.get("default")
    if default is None:
        return "—"
    if isinstance(default, bool):
        return md_code(str(default).lower(), in_table=True)
    if isinstance(default, str):
        return md_code(f'"{default}"' if default else '""', in_table=True)
    return md_code(default, in_table=True)


def split_description(text: str) -> tuple[str, str]:
    """Split a function description into (what it does, data requirements)."""
    if DATA_REQUIREMENTS_MARKER in text:
        head, _, tail = text.partition(DATA_REQUIREMENTS_MARKER)
        return head.strip(), tail.strip()
    return text.strip(), ""


def table(header: list[str], rows: list[list[str]], align: list[str] | None = None) -> str:
    align = align or ["---"] * len(header)
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(align) + " |"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def slug(heading: str) -> str:
    """The anchor MyST gives a heading (``myst_heading_anchors``): lower-case, spaces to ``-``, punctuation dropped."""
    return re.sub(r"[^\w一-鿿\- ]", "", heading.strip().lower().replace(" ", "-"))


def category_title(category: str) -> str:
    if category in CATEGORIES:
        return CATEGORIES[category][0]
    return category.replace("_", " ").capitalize()


def category_order(servers: dict[str, Server]) -> list[str]:
    seen = {fn.category for s in servers.values() for fn in s.functions}
    known = [c for c in CATEGORIES if c in seen]
    extra = sorted(c for c in seen if c not in CATEGORIES and c != UNCATEGORISED)
    tail = [UNCATEGORISED] if UNCATEGORISED in seen else []
    return known + extra + tail


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render_index(servers: dict[str, Server], in_process: dict[str, list[InProcessTool]]) -> str:
    order = category_order(servers)
    n_servers = len(servers)
    n_functions = sum(1 for s in servers.values() for fn in s.functions if fn.wired)
    n_in_process = sum(len(v) for v in in_process.values())
    lines = [
        GENERATED_NOTE,
        "",
        "# Analysis tools",
        "",
        "ST-Coscientist works with two kinds of tools.",
        "",
        f"**MCP tools** are the analysis methods: {n_functions} functions served by {n_servers} Model Context "
        "Protocol (MCP) servers, each running in its own conda environment so that methods with incompatible "
        "dependencies coexist on one machine. They are grouped into *skill categories*, which is how the agent "
        "routes a task to candidate tools and how `sog-setup` lets you choose what to install. One page per "
        "category follows; every function is listed with its parameters.",
        "",
        f"**In-process research tools** are {n_in_process} Python functions the agent imports and calls inside "
        "its own interpreter: database queries, expression atlases, literature search, pharmacology lookups and "
        "light utilities. They need nothing beyond the agent environment. See [In-process research tools]"
        "(in-process.md).",
        "",
        "```{tip}",
        "The agent only sees MCP tools after they are wired in: `stcoscientist --mcp` on the command line, or "
        "`agent.add_mcp()` from Python. `sog-setup` builds the conda environments and records which servers are "
        "ready in `install/recipes/mcp_config.setup.yaml`.",
        "```",
        "",
        "## Skill categories",
        "",
    ]
    rows = []
    for category in order:
        primary = [s for s in servers.values() if s.primary_category == category]
        n_fn = sum(1 for s in servers.values() for fn in s.functions if fn.category == category and fn.wired)
        blurb = CATEGORIES.get(category, ("", ""))[1]
        rows.append(
            [
                f"[{category_title(category)}]({category}.md)",
                md_code(category, in_table=True),
                str(len(primary)),
                str(n_fn),
                md_text(blurb, in_table=True),
            ]
        )
    lines.append(
        table(
            ["Category", "Key", "Servers", "Functions", "What it covers"],
            rows,
            ["---", "---", "---:", "---:", "---"],
        )
    )
    lines += [
        "",
        "A server is listed under the category of its first function; a function from another category is marked "
        "on its server's page. The counts above are read from `install/recipes/tool_specs/` and "
        "`agent/MCP_server/mcp_config.yaml` at build time, so they always match the checkout the documentation "
        "was built from.",
        "",
        "## How a tool runs",
        "",
        "Each MCP server is a small Python *portal* (`agent/tools/<key>_mcp_server.py`) that the agent starts. The "
        "portal publishes the server's functions over MCP and, for each call, runs a *worker* "
        "(`<key>_worker.py` or `<key>_worker.R`) under the method's own interpreter, which "
        "`agent/MCP_server/mcp_config.yaml` names through the `<PREFIX>_PYTHON` (or `_RSCRIPT`) and "
        "`<PREFIX>_WORKER` variables. The worker reads the input files, runs the method and replies with a JSON "
        "document (status, result files, parameters used, summary); the portal hands it back to the agent. See "
        "[Architecture: MCP tools](../architecture/mcp-tools.md).",
        "",
        "## Notes",
        "",
    ]
    multi = [s for s in servers.values() if len(s.categories) > 1]
    if multi:
        lines += ["### Servers in more than one category", ""]
        lines.append(
            table(
                ["Server", "Listed under", "Also"],
                [
                    [
                        md_code(s.key, in_table=True),
                        category_title(s.categories[0]),
                        ", ".join(category_title(c) for c in s.categories[1:]),
                    ]
                    for s in multi
                ],
            )
        )
        lines.append("")
    env_users: dict[str, list[str]] = defaultdict(list)
    for s in servers.values():
        if s.env:
            env_users[s.env].append(s.key)
    shared = {env: keys for env, keys in env_users.items() if len(keys) > 1}
    if shared:
        lines += ["### Conda environments shared by more than one server", ""]
        lines.append(
            table(
                ["Env", "Servers"],
                [
                    [md_code(env, in_table=True), ", ".join(md_code(k, in_table=True) for k in keys)]
                    for env, keys in sorted(shared.items())
                ],
            )
        )
        lines.append("")
    disabled = [s.key for s in servers.values() if not s.enabled]
    if disabled:
        lines += [
            "### Servers disabled in the canonical config",
            "",
            ", ".join(md_code(k) for k in disabled) + ".",
            "",
        ]
    lines += [
        "```{toctree}",
        ":hidden:",
        ":maxdepth: 1",
        "",
    ]
    lines.extend(f"{category}" for category in order)
    lines += ["in-process", "```", ""]
    return "\n".join(lines)


def render_category(category: str, servers: dict[str, Server]) -> str:
    title, blurb = CATEGORIES.get(category, (category_title(category), ""))
    members = sorted(
        (s for s in servers.values() if any(fn.category == category for fn in s.functions)),
        key=lambda s: (s.primary_category != category, s.key),
    )
    lines = [GENERATED_NOTE, "", f"# {title}", ""]
    if blurb:
        lines += [md_text(blurb), ""]
    n_fn = sum(1 for s in members for fn in s.functions if fn.category == category and fn.wired)
    guests = [s for s in members if s.primary_category != category]
    guest_note = (
        f" ({len(guests)} of them listed under another category: {', '.join(md_code(s.key) for s in guests)})"
        if guests
        else ""
    )
    lines += [
        f"Skill category `{category}`: {n_fn} function(s) from {len(members)} server(s){guest_note}. "
        "Install the whole category with `sog-setup` (pick it in the skill menu), or one server with "
        "`sog-setup --only <key>`.",
        "",
        "## Servers",
        "",
    ]
    rows = []
    for s in members:
        fns = ", ".join(
            f"[{md_code(fn.name, in_table=True)}](#{slug(fn.name)})"
            + ("" if fn.category == category else f" ({category_title(fn.category)})")
            for fn in s.functions
        )
        env = md_code(s.env, in_table=True) if s.env else "—"
        if not s.builds_env and s.env:
            env += " (no build)"
        worker = "R" if s.worker_kind == "r" else "Python"
        rows.append([f"[{md_code(s.key, in_table=True)}](#{slug(s.key)})", fns, env, worker, "yes" if s.gpu else "no"])
    lines.append(table(["Server", "Functions", "Conda env", "Worker", "GPU"], rows))
    lines += [
        "",
        "*Conda env* is the environment `sog-setup` builds for the server; *(no build)* marks a server that runs in "
        "an interpreter that already exists. *GPU* says whether the recipe wants one.",
        "",
    ]

    for s in members:
        lines += [f"## {s.key}", ""]
        if s.description:
            lines += [md_text(s.description), ""]
        facts = [f"- **Portal:** {md_code(s.portal) if s.portal else '—'}"]
        if s.worker:
            facts.append(f"- **Worker:** {md_code(s.worker)} ({'R' if s.worker_kind == 'r' else 'Python'})")
        if s.env:
            facts.append(f"- **Conda env:** {md_code(s.env)}" + ("" if s.builds_env else " (no build)"))
        facts.append(f"- **GPU:** {'yes' if s.gpu else 'no'}")
        if s.est_gb:
            facts.append(f"- **Estimated size:** {s.est_gb} GB")
        if not s.enabled:
            facts.append("- **Disabled in the canonical config**")
        lines += [*facts, ""]
        for fn in s.functions:
            lines += [f"### {fn.name}", ""]
            if fn.category != category:
                lines += [f"*Listed under [{category_title(fn.category)}]({fn.category}.md).*", ""]
            what, data = split_description(fn.description)
            if what:
                lines += [md_text(what), ""]
            if data:
                lines += ["```{admonition} Data requirements", ":class: note", "", md_text(data), "```", ""]
            if fn.parameters:
                lines.append(
                    table(
                        ["Parameter", "Type", "Required", "Default", "Description"],
                        [
                            [
                                md_code(p["name"], in_table=True),
                                md_code(p["type"], in_table=True) if p["type"] else "—",
                                "yes" if p["required"] else "no",
                                md_default(p),
                                md_text(p["description"], in_table=True),
                            ]
                            for p in fn.parameters
                        ],
                    )
                )
                lines.append("")
            elif not fn.wired:
                lines += ["*In the spec but not wired in the canonical config, so no parameters are published.*", ""]
    return "\n".join(lines)


def _param_cell(params: list[dict[str, Any]]) -> str:
    return ", ".join(md_code(p.get("name", ""), in_table=True) for p in params if p.get("name")) or "—"


def render_in_process(in_process: dict[str, list[InProcessTool]]) -> str:
    n = sum(len(v) for v in in_process.values())
    lines = [
        GENERATED_NOTE,
        "",
        "# In-process research tools",
        "",
        f"{n} Python functions in {len(in_process)} subject modules under `spatialomicsgym.tool`. The agent imports "
        "them in its own interpreter (`from spatialomicsgym.tool.<module> import <function>`) when a task needs a "
        "database query, an atlas lookup, a literature search or a light analysis step, so they need no conda "
        "environment of their own. Each entry links to the function's signature in the API reference.",
        "",
        "```{note}",
        "Some tools call external services and read a credential from the environment when one is needed "
        "(`PROTOCOLS_IO_ACCESS_TOKEN`, `SYNAPSE_AUTH_TOKEN`, `NCBI_EMAIL`, ...); see "
        "[Configuration](../configuration.md). Outbound requests go through the package's HTTP client, which "
        "enforces the egress policy in `agent/spatialomicsgym/policy/egress.yaml`.",
        "```",
        "",
        "## Modules",
        "",
    ]
    rows = [
        [f"[{md_code(f'spatialomicsgym.tool.{module}', in_table=True)}](#{slug(module)})", str(len(tools))]
        for module, tools in in_process.items()
    ]
    lines.append(table(["Module", "Tools"], rows, ["---", "---:"]))
    lines.append("")
    for module, tools in in_process.items():
        lines += [f"## {module}", ""]
        rows = []
        for t in tools:
            if t.name.isidentifier():
                ref = f"{{py:func}}`~spatialomicsgym.tool.{module}.{t.name}`"
            else:
                ref = md_code(t.name, in_table=True)
            rows.append([ref, _param_cell(t.required), _param_cell(t.optional), md_text(t.description, in_table=True)])
        lines.append(table(["Function", "Required", "Optional", "What it does"], rows))
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Writing
# --------------------------------------------------------------------------- #
def _write(path: Path, text: str) -> bool:
    """Write ``text`` to ``path`` if it changed; return whether it was written (keeps rebuilds incremental)."""
    if not text.endswith("\n"):
        text += "\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def substitutions() -> dict[str, str]:
    """The headline counts, for ``myst_substitutions``: ``{{ n_servers }}`` and friends in hand-written pages."""
    servers = read_servers()
    in_process = read_in_process_tools()
    n_servers = len(servers)
    n_functions = sum(1 for s in servers.values() for fn in s.functions if fn.wired)
    n_in_process = sum(len(v) for v in in_process.values())
    return {
        "n_servers": str(n_servers),
        "n_mcp_functions": str(n_functions),
        "n_in_process": str(n_in_process),
        "n_tools_total": str(n_functions + n_in_process),
    }


def generate(output_dir: Path = OUTPUT_DIR) -> list[Path]:
    servers = read_servers()
    in_process = read_in_process_tools()
    written: list[Path] = []
    pages = {"index.md": render_index(servers, in_process), "in-process.md": render_in_process(in_process)}
    for category in category_order(servers):
        pages[f"{category}.md"] = render_category(category, servers)
    for name, text in pages.items():
        if _write(output_dir / name, text):
            written.append(output_dir / name)
    # Remove pages for categories that no longer exist, so a stale file never lingers in the toctree.
    for stale in output_dir.glob("*.md"):
        if stale.name not in pages:
            stale.unlink()
    return written


# --------------------------------------------------------------------------- #
# Sphinx hooks
# --------------------------------------------------------------------------- #
def _on_builder_inited(app: Sphinx) -> None:
    from sphinx.util import logging

    logger = logging.getLogger(__name__)
    try:
        written = generate(Path(app.srcdir) / "tools")
    except FileNotFoundError as exc:
        logger.warning("tool catalogue not generated: %s", exc)
        return
    logger.info("tool catalogue: %d page(s) (re)generated under docs/tools/", len(written))


def setup(app: Sphinx) -> dict[str, Any]:
    app.connect("builder-inited", _on_builder_inited)
    return {"version": "1.0", "parallel_read_safe": True, "parallel_write_safe": True}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/tools/*.md from the tool specs and the MCP config.")
    parser.add_argument("--output", type=Path, default=OUTPUT_DIR, help=f"directory to write (default: {OUTPUT_DIR})")
    args = parser.parse_args(argv)
    written = generate(args.output)
    for path in written:
        print(f"wrote {path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path}")
    print(f"{len(written)} page(s) written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
