"""MCP tool knowledge base for spatial analysis.

Contains metadata about available tools for spatial transcriptomics analysis,
QC, preprocessing, imputation, factorization, and multiomics integration.
"""

from __future__ import annotations

from typing import Any

SPATIAL_ANALYSIS_MCP_TOOLS: dict[str, dict[str, Any]] = {
    "dataset_library": {
        "task": "data_access",
        "mcp_function": "search_spatial_datasets",
        "full_name": "Spatial Dataset Library Search",
        "description": "Find a built-in spatial dataset when the user named no data file path.",
        "gpu": False,
        "priority": 1,
    },
    "squidpy_neighbors": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_spatial_neighbors",
        "full_name": "Squidpy Spatial Neighbors",
        "description": "Build spatial neighbor graphs from spatial transcriptomics data using Squidpy.",
        "gpu": False,
        "priority": 1,
    },
    "squidpy_nhood": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_nhood_enrichment",
        "full_name": "Squidpy Neighborhood Enrichment",
        "description": "Compute neighborhood enrichment scores to identify co-localization patterns between cell types.",
        "gpu": False,
        "priority": 1,
    },
    "squidpy_centrality": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_centrality_scores",
        "full_name": "Squidpy Centrality Scores",
        "description": "Calculate centrality scores to characterize spatial organization of cell type clusters.",
        "gpu": False,
        "priority": 1,
    },
    "squidpy_co_occurrence": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_co_occurrence",
        "full_name": "Squidpy Co-occurrence",
        "description": "Compute spatial co-occurrence probability of cell types across spatial dimensions.",
        "gpu": False,
        "priority": 1,
    },
    "squidpy_ripley": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_ripley",
        "full_name": "Squidpy Ripley Statistics",
        "description": "Compute Ripley's statistics to test for spatial randomness or clustering of cell types.",
        "gpu": False,
        "priority": 2,
    },
    "squidpy_autocorr": {
        "task": "spatial_analysis",
        "mcp_function": "squidpy_spatial_autocorr",
        "full_name": "Squidpy Spatial Autocorrelation",
        "description": "Compute Moran's I or Geary's C to measure spatial autocorrelation of gene expression.",
        "gpu": False,
        "priority": 2,
    },
    "seurat_qc": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_qc_cluster",
        "full_name": "Seurat QC and Clustering",
        "description": "Perform quality control, normalization, and clustering of single-cell data using Seurat.",
        "gpu": False,
        "priority": 1,
    },
    "seurat_integrate": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_integrate_qc_cluster",
        "full_name": "Seurat Integration QC Clustering",
        "description": "Integrate multiple single-cell datasets with QC and clustering using Seurat's integration methods.",
        "gpu": False,
        "priority": 1,
    },
    "seurat_markers": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_find_markers",
        "full_name": "Seurat Find Markers",
        "description": "Identify differentially expressed marker genes for clusters or conditions using Seurat.",
        "gpu": False,
        "priority": 1,
    },
    "seurat_dimplot": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_dimplot",
        "full_name": "Seurat Dimension Plot",
        "description": "Generate UMAP or tSNE dimension reduction plots colored by cluster or metadata using Seurat.",
        "gpu": False,
        "priority": 2,
    },
    "seurat_spatial_qc": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_spatial_qc_cluster",
        "full_name": "Seurat Spatial QC Clustering",
        "description": "Perform quality control, normalization, and clustering of Visium spatial transcriptomics data.",
        "input_requirements": {"images": True},
        "gpu": False,
        "priority": 1,
    },
    "seurat_spatial_feature": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_spatial_feature_plot",
        "full_name": "Seurat Spatial Feature Plot",
        "description": "Visualize gene expression overlaid on spatial tissue coordinates using Seurat.",
        "gpu": False,
        "priority": 2,
    },
    "seurat_spatial_dimplot": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_spatial_dimplot",
        "full_name": "Seurat Spatial Dimension Plot",
        "description": "Plot spatial transcriptomics clusters overlaid on tissue histology images using Seurat.",
        "gpu": False,
        "priority": 2,
    },
    "seurat_spatial_svg": {
        "task": "spatial_analysis",
        "mcp_function": "seurat_spatial_variable_features",
        "full_name": "Seurat Spatial Variable Features",
        "description": "Identify spatially variable genes in Visium data using Seurat's spatial feature selection.",
        "input_requirements": {"images": True},
        "gpu": False,
        "priority": 2,
    },
    "xfuse_spatial_analysis": {
        "task": "spatial_analysis",
        "mcp_function": "xfuse_spatial_analysis",
        "full_name": "XFuse Spatial Analysis",
        "description": "Run XFuse super-resolution end-to-end from a spatial h5ad (the entry point for h5ad input).",
        "input_requirements": {"images": True},
        "gpu": False,
        "priority": 3,
    },
    "xfuse": {
        "task": "spatial_analysis",
        "mcp_function": "xfuse_run",
        "full_name": "XFuse Run",
        "description": "Run XFuse from an existing XFuse-format .h5 and TOML config, not from an h5ad.",
        "input_requirements": {"images": True},
        "gpu": False,
        "priority": 3,
    },
    "xfuse_config": {
        "task": "spatial_analysis",
        "mcp_function": "xfuse_build_config",
        "full_name": "XFuse Build Config",
        "description": "Build a configuration file for the XFuse spatial resolution enhancement pipeline.",
        "gpu": False,
        "priority": 3,
    },
    "spatialpca": {
        "task": "spatial_analysis",
        "mcp_function": "run_spatialpca",
        "full_name": "SpatialPCA",
        "description": "Run SpatialPCA to extract spatially aware low-dimensional representations of tissue structure.",
        "gpu": False,
        "priority": 2,
    },
    "istar_check": {
        "task": "spatial_analysis",
        "mcp_function": "istar_check_dataset",
        "full_name": "iSTAR Check Dataset",
        "description": "Validate dataset format and completeness for the iSTAR spatial super-resolution pipeline.",
        "gpu": False,
        "priority": 3,
    },
    "istar_pipeline": {
        "task": "spatial_analysis",
        "mcp_function": "istar_full_pipeline",
        "full_name": "iSTAR Full Pipeline",
        "description": "Run the full iSTAR pipeline for image-guided spatial transcriptomics super-resolution.",
        "input_requirements": {"images": True},
        "gpu": False,
        "priority": 3,
    },
    "prost_pnn": {
        "task": "spatial_analysis",
        "mcp_function": "prost_pnn_domains",
        "full_name": "PROST PNN Domains",
        "description": (
            "Identify spatial domains with PROST PNN (PROST's neural-network clustering on PROST-Index-selected, "
            "normalised and log-transformed genes)."
        ),
        "gpu": False,
        "priority": 3,
    },
    "spatialprompt_cluster": {
        "task": "spatial_analysis",
        "mcp_function": "spatialprompt_cluster",
        "full_name": "SpatialPrompt Cluster",
        "description": (
            "Segment a slide into spatial domains with SpatialPrompt's SpatialCluster (KMeans on its 1000 most "
            "variable genes plus their spatial-neighbourhood average); no reference needed."
        ),
        "gpu": False,
        "priority": 2,
    },
    "spacel_scube": {
        "task": "spatial_analysis",
        "mcp_function": "run_spacel_scube",
        "full_name": "SPACEL sCube",
        "description": "Align two or more serial slices into one 3D coordinate frame with SPACEL's Scube, on a label column shared by every slice.",
        "gpu": False,
        "priority": 3,
    },
    "moscot": {
        "task": "spatial_analysis",
        "mcp_function": "moscot_run",
        "full_name": "MOSCOT Run",
        "description": "Apply MOSCOT optimal transport framework for spatial multi-sample trajectory analysis.",
        "gpu": False,
        "priority": 2,
    },
    "spotclean": {
        "task": "qc_preprocessing",
        "mcp_function": "run_spotclean",
        "full_name": "SpotClean",
        "description": "Remove contamination from ambient RNA in spatial transcriptomics data using SpotClean.",
        "gpu": False,
        "priority": 2,
    },
    "spotsweeper": {
        "task": "qc_preprocessing",
        "mcp_function": "run_spotsweeper",
        "full_name": "SpotSweeper",
        "description": "Flag low-quality spots (local outliers) and regional artifacts in spatial transcriptomics data using SpotSweeper; spots are flagged in a QC table, not removed.",
        "gpu": False,
        "priority": 2,
    },
    "mist": {
        "task": "spatial_imputation",
        "mcp_function": "mist_regions_impute",
        "full_name": "MIST Regions Impute",
        "description": (
            "Detect spatial regions with MIST/ReST and fill zeros with ReST's spKNN neighbour-mean imputation "
            "(MIST's ensemble imputer is not run)."
        ),
        "gpu": False,
        "priority": 2,
    },
    "stplus": {
        "task": "spatial_imputation",
        "mcp_function": "run_stplus",
        "full_name": "stPlus",
        "description": "Impute unmeasured spatial genes with stPlus: an autoencoder trained on spots and a single-cell reference, then a KNN transfer of reference expression.",
        "input_requirements": {"sc_reference": True},
        "gpu": False,
        "priority": 2,
    },
    "spotgf": {
        "task": "spatial_imputation",
        "mcp_function": "spotgf_denoise",
        "full_name": "SpotGF Denoise",
        "description": (
            "Denoise a GEM-format spatial file with SpotGF: score each gene's spatial spread against the tissue "
            "outline by optimal transport and write GEMs that keep the high-scoring genes."
        ),
        "gpu": False,
        "priority": 3,
    },
    "spicemix": {
        "task": "spatial_factorization",
        "mcp_function": "run_spicemix",
        "full_name": "SpiceMix",
        "description": "Perform spatially-informed non-negative matrix factorization of spatial transcriptomics data.",
        "gpu": False,
        "priority": 3,
    },
    "svca": {
        "task": "variance_analysis",
        "mcp_function": "svca_variance_decomposition",
        "full_name": "SVCA Variance Decomposition",
        "description": "Decompose each gene's expression variance into a spatial fraction and residual noise using SVCA (exact two-component FaST-LMM fit over every in-tissue spot; the environmental / cell-cell term is not estimated).",
        "gpu": False,
        "priority": 3,
    },
    "spatialglue": {
        "task": "multiomics_integration",
        "mcp_function": "spatialglue_integrate",
        "full_name": "SpatialGlue Integrate",
        "description": "Integrate spatial multi-omics modalities using SpatialGlue's graph attention network.",
        "gpu": False,
        "priority": 2,
    },
    # Functional enrichment lives in this family on purpose: the front door pins nine task cards
    # derived from the skill families, and families already mix task tokens (data_access +
    # spatial_analysis above), so a new token here costs no new family.
    "pathway_enrichment": {
        "task": "functional_enrichment",
        "mcp_function": "run_pathway_enrichment",
        "full_name": "Pathway Enrichment (decoupler ORA / GSEA-prerank)",
        "description": "Gene-set over-representation and GSEA-prerank on a ranked gene table (SVGs, domain markers) against MSigDB collections.",
        "gpu": False,
        "priority": 1,
    },
    "pathway_activity": {
        "task": "functional_enrichment",
        "mcp_function": "run_pathway_activity",
        "full_name": "Per-spot Pathway Activity (decoupler PROGENy / hallmark)",
        "description": "Score PROGENy signalling pathways or hallmark gene sets in every spot of a spatial h5ad and map them on the tissue.",
        "gpu": False,
        "priority": 1,
    },
    # Visualization, under the same rule as functional enrichment above: a new task token, no new
    # family. These are the doorway, not the catalogue -- the long tail of plot families is
    # discovered through `list_visualization_capabilities`, which is what a capability registry is
    # for. Listing every plot type here would grow the synthetic skills-catalog candidate that
    # enters retrieval on EVERY query, including the ones that want nothing drawn.
    #
    # The four reads come first because the model should look before it draws: a plot request that
    # the data cannot support comes back naming what is missing and what would produce it, which is
    # only possible if the dataset was profiled first.
    "viz_inspect": {
        "task": "visualization",
        "mcp_function": "inspect_dataset",
        "full_name": "Inspect a Dataset for Plotting",
        "description": "Profile an h5ad once and report what it holds -- layers, embeddings, coordinates, images, annotations, stored results -- and which plots it can support as it stands.",
        "gpu": False,
        "priority": 1,
    },
    "viz_capabilities": {
        "task": "visualization",
        "mcp_function": "list_visualization_capabilities",
        "full_name": "List Visualization Capabilities",
        "description": "The plot catalogue: what can be drawn, what each plot needs, and what is unsupported here and why.",
        "gpu": False,
        "priority": 2,
    },
    "viz_recommend": {
        "task": "visualization",
        "mcp_function": "recommend_visualizations",
        "full_name": "Recommend Visualizations",
        "description": "A short, ordered list of the plots worth drawing for this dataset and question, rather than everything that could be drawn.",
        "gpu": False,
        "priority": 1,
    },
    "viz_validate": {
        "task": "visualization",
        "mcp_function": "validate_plot_request",
        "full_name": "Validate a Plot Request",
        "description": "Check a plot and its parameters against the dataset before drawing; refusals name the missing field and the call that would produce it.",
        "gpu": False,
        "priority": 2,
    },
    "viz_spatial_expression": {
        "task": "visualization",
        "mcp_function": "plot_spatial_expression",
        "full_name": "Spatial Expression Map",
        "description": "Paint genes, a numeric column or one column of a score matrix on the tissue, optionally over the histology image at true spot size.",
        "gpu": False,
        "priority": 1,
    },
    "viz_spatial_annotation": {
        "task": "visualization",
        "mcp_function": "plot_spatial_annotation",
        "full_name": "Spatial Annotation Map",
        "description": "Paint a categorical annotation -- domain, cell type or cluster -- on the tissue, as one map or one panel per level.",
        "gpu": False,
        "priority": 1,
    },
    "viz_embedding": {
        "task": "visualization",
        "mcp_function": "plot_embedding",
        "full_name": "Embedding Scatter",
        "description": "Scatter a stored UMAP, t-SNE, PCA or diffusion map coloured by genes or metadata, faceted or split by a grouping.",
        "gpu": False,
        "priority": 1,
    },
    "viz_qc_report": {
        "task": "visualization",
        "mcp_function": "generate_qc_report",
        "full_name": "Quality-Control Report",
        "description": "Counts, detected genes and mitochondrial fraction as distributions and, when there are coordinates, on the tissue.",
        "gpu": False,
        "priority": 1,
    },
    "viz_differential": {
        "task": "visualization",
        "mcp_function": "plot_differential_expression",
        "full_name": "Differential Expression Figure",
        "description": "Volcano, ranked markers or a heatmap from a STORED differential-expression result; a ranking with no fold changes and no p-values is refused, never plotted with the test statistic on an effect-size axis.",
        "gpu": False,
        "priority": 1,
    },
    "viz_deconvolution": {
        "task": "visualization",
        "mcp_function": "plot_deconvolution",
        "full_name": "Deconvolution Proportion Maps",
        "description": "Per-cell-type proportion maps, the dominant type per spot, or a composition summary, from a deconvolution's obsm or its proportions CSV.",
        "gpu": False,
        "priority": 1,
    },
    "viz_markers": {
        "task": "visualization",
        "mcp_function": "plot_marker_expression",
        "full_name": "Marker Expression Across Groups",
        "description": "Marker genes per cluster or cell type as a dot plot, violins or a heatmap, or the composition of one annotation across another.",
        "gpu": False,
        "priority": 1,
    },
    "viz_pathway": {
        "task": "visualization",
        "mcp_function": "plot_pathway_results",
        "full_name": "Pathway Result Figure",
        "description": "Enriched terms from a stored enrichment table, or per-spot pathway activity on the tissue. Runs no enrichment of its own.",
        "gpu": False,
        "priority": 1,
    },
    "viz_organisation": {
        "task": "visualization",
        "mcp_function": "plot_spatial_statistics",
        "full_name": "Tissue Organisation Figure",
        "description": "The spatial neighbour graph, or neighbourhood enrichment, autocorrelation and co-occurrence as the spatial-statistics tool computed them.",
        "gpu": False,
        "priority": 1,
    },
    "viz_trajectory": {
        "task": "visualization",
        "mcp_function": "plot_trajectory",
        "full_name": "Pseudotime Figure",
        "description": "A stored pseudotime on an embedding, on the tissue, or as gene trends along the ordering; captioned as an ordering with no units, never as time.",
        "gpu": False,
        "priority": 2,
    },
    "viz_communication": {
        "task": "visualization",
        "mcp_function": "plot_cell_communication",
        "full_name": "Cell-Communication Figure",
        "description": "An inferred ligand-receptor result as a sender-by-receiver matrix or a ranking of pairs; every caption says inferred, not measured.",
        "gpu": False,
        "priority": 2,
    },
    # Three dimensions. Reaching for plot_spatial_expression on a merged serial-section object
    # draws every section overlaid in one frame, which looks like a figure and is not one.
    "viz_spatial_3d": {
        "task": "visualization",
        "mcp_function": "plot_spatial_3d",
        "full_name": "Three-Dimensional Stack Figure",
        "description": "A reconstructed stack from three fixed angles, its depth profile, or a value binned along an anatomical axis; the z is read, never invented.",
        "gpu": False,
        "priority": 2,
    },
    "viz_section_grid": {
        "task": "visualization",
        "mcp_function": "plot_section_grid",
        "full_name": "Section Grid",
        "description": "One panel per section on one shared colour scale. Use on any object holding more than one section; the tissue-map functions panel per gene, not per section.",
        "gpu": False,
        "priority": 1,
    },
    "viz_alignment_qc": {
        "task": "visualization",
        "mcp_function": "plot_alignment_qc",
        "full_name": "Alignment Before and After",
        "description": "One adjacent pair drawn from the pre-alignment frame and the aligned frame side by side, with that pair's centroid offset in both. Read the pair, not the stack.",
        "gpu": False,
        "priority": 2,
    },
    "viz_compose": {
        "task": "visualization",
        "mcp_function": "compose_figure",
        "full_name": "Compose a Contact Sheet",
        "description": "Place several finished figures on one sheet that indexes them, stating that panels drawn separately are not comparable.",
        "gpu": False,
        "priority": 2,
    },
    "viz_export": {
        "task": "visualization",
        "mcp_function": "export_visualization",
        "full_name": "Export a Figure for Publication",
        "description": "Re-render a figure as SVG, PNG or PDF and ship the numbers it was drawn from beside it, optionally as one zip.",
        "gpu": False,
        "priority": 2,
    },
    "viz_pipeline": {
        "task": "visualization",
        "mcp_function": "run_visualization_pipeline",
        "full_name": "Adaptive Visualization Report",
        "description": "Inspect a dataset, draw the few figures worth drawing against a small budget, and name what was left out and what needs a choice.",
        "gpu": False,
        "priority": 1,
    },
    "viz_update": {
        "task": "visualization",
        "mcp_function": "update_visualization",
        "full_name": "Revise an Existing Figure",
        "description": "Change an existing figure's colour, scale, ordering, point size or panel layout from its saved spec, without redoing the analysis behind it.",
        "gpu": False,
        "priority": 1,
    },
}
