"""Generate ``agent/tools/CATALOG.md``: every MCP portal in ``agent/tools/``, grouped by analysis category.

``agent/tools/`` stays flat on purpose (its ``README.md`` gives the reasons), so a reader looking for
"the deconvolution tools" has no folder to open. This page is that view. Nothing reads it at runtime:
the agent wires portals from ``agent/MCP_server/mcp_config.yaml``, and the page is neither a ``.py`` nor
an ``.R`` file, so it reaches no source pin, wheel payload or sdist include.

Where each column comes from:

* category, portal, worker and conda env: the per-server specs, ``install/recipes/tool_specs/<key>.yaml``
  (a function's ``category`` is the skill that lists it, copied in by ``sog-setup capture``);
* functions and the one-line description: the canonical config, because that is what the agent is handed.

The notes at the end list every place the two sources disagree, and every portal file neither of them names.

Usage::

    python -m sog_install.tools_catalog            # print the catalogue
    python -m sog_install.tools_catalog --write    # rewrite agent/tools/CATALOG.md
    python -m sog_install.tools_catalog --check    # exit 1 when agent/tools/CATALOG.md is stale

The output is deterministic: no timestamps, no absolute paths, a fixed order. Stdlib + PyYAML only. No
runtime module imports this file and the ``sog-setup`` CLI does not dispatch to it.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath

import yaml

from . import constants
from .categories import CATEGORY_ALIASES
from .specs import ToolSpec, load_all_specs

#: Repository-relative names, used in the page and in messages (never an absolute path).
CATALOG_REL = "agent/tools/CATALOG.md"
SPECS_REL = "install/recipes/tool_specs"
CONFIG_REL = "agent/MCP_server/mcp_config.yaml"
TOOLS_REL = "agent/tools"

GENERATE_COMMAND = "python -m sog_install.tools_catalog --write"
CHECK_COMMAND = "python -m sog_install.tools_catalog --check"
HEADER = f"<!-- generated by {GENERATE_COMMAND}; edit the specs or the config, not this file -->"

PORTAL_SUFFIX = "_mcp_server.py"
UNCATEGORISED = "uncategorised"
DESCRIPTION_WIDTH = 160

# The first sentence ends at a full stop followed by whitespace or the end, except after a common abbreviation.
_SENTENCE_END = re.compile(r"(?<!\be\.g)(?<!\bi\.e)(?<!\bvs)(?<!\bal)\.(?=\s|$)")


@dataclass
class Server:
    """One MCP server as the catalogue shows it."""

    key: str
    portal: str = ""  # basename of the portal file
    worker: str = ""  # basename of the worker file, "" when the server has none
    env: str = ""  # display text for the conda env
    functions: list[str] = field(default_factory=list)  # wired functions, config order
    fn_category: dict[str, str] = field(default_factory=dict)  # function -> spec category
    categories: list[str] = field(default_factory=list)  # spec categories, first-listed function first
    description: str = ""
    enabled: bool = True

    @property
    def primary(self) -> str:
        return self.categories[0] if self.categories else UNCATEGORISED


@dataclass
class Catalog:
    servers: dict[str, Server]
    unwired_portals: list[str]  # portal files on disk that no spec and no config entry names
    drift: list[str]  # one line per disagreement between the specs and the config
    spec_env: dict[str, str]  # server key -> source env (only servers with one)


# --------------------------------------------------------------------------- #
# Reading
# --------------------------------------------------------------------------- #
def _env_of_interpreter(path: str) -> str:
    """The conda env an interpreter path lives in: ``.../envs/<name>/bin/x`` -> ``<name>``; a base ``bin/`` -> ``base``."""
    parts = PurePosixPath(str(path)).parts
    if "envs" in parts:
        i = parts.index("envs")
        if i + 1 < len(parts):
            return parts[i + 1]
    return "base" if "bin" in parts else ""


def _interpreter_env(env_vars: dict) -> str:
    """The env of the first interpreter variable (``*_PYTHON`` / ``*_RSCRIPT``), by variable name."""
    for var in sorted(env_vars):
        if var.endswith(("_PYTHON", "_RSCRIPT")):
            name = _env_of_interpreter(env_vars[var])
            if name:
                return name
    return ""


def _basename(value) -> str:
    return PurePosixPath(str(value)).name if value else ""


def _config_portal(entry: dict) -> str:
    command = entry.get("command") or []
    return next((_basename(arg) for arg in command if str(arg).endswith(".py")), "")


def _config_worker(entry: dict, worker_var: str = "") -> str:
    env = entry.get("env") or {}
    if worker_var and env.get(worker_var):
        return _basename(env[worker_var])
    return next((_basename(env[v]) for v in sorted(env) if v.endswith("_WORKER") and env[v]), "")


def one_line(text: str, width: int = DESCRIPTION_WIDTH) -> str:
    """The first sentence of ``text`` on one line, cut at a word boundary to ``width``, safe in a table cell."""
    text = " ".join(str(text or "").split())
    end = _SENTENCE_END.search(text)
    if end:
        text = text[: end.end()]
    if len(text) > width:
        cut = text[: width - 3]
        space = cut.rfind(" ")
        if space >= width // 2:
            cut = cut[:space]
        text = cut.rstrip(" ,;:") + "..."
    if text.count("`") % 2:  # a code span cut in half would swallow the rest of the row
        text = text.replace("`", "")
    return text.replace("|", "\\|")


def read_catalog(root: Path) -> Catalog:
    """Gather the catalogue for the checkout at ``root`` from its specs, its canonical config and ``agent/tools/``."""
    specs_dir = constants.recipes_root(root) / "tool_specs"
    config_path = constants.agent_root(root) / "MCP_server" / "mcp_config.yaml"
    tools_dir = constants.tools_dir(root)
    if not specs_dir.is_dir():
        raise FileNotFoundError(f"no tool specs at {SPECS_REL} under {root}")
    if not config_path.is_file():
        raise FileNotFoundError(f"no canonical config at {CONFIG_REL} under {root}")

    specs: dict[str, ToolSpec] = load_all_specs(specs_dir)
    config = (yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}).get("mcp_servers") or {}
    portals_on_disk = sorted(p.name for p in tools_dir.glob(f"*{PORTAL_SUFFIX}"))

    servers: dict[str, Server] = {}
    drift: list[str] = []
    for key in sorted(set(specs) | set(config)):
        spec, entry = specs.get(key), config.get(key)
        server = Server(key=key)
        if entry is not None:
            server.functions = [
                t["spatialomicsgym_name"] for t in entry.get("tools") or [] if t.get("spatialomicsgym_name")
            ]
            server.description = one_line(entry.get("description", ""))
            server.enabled = entry.get("enabled", True) is not False
        if spec is not None:
            server.portal = spec.server_file
            server.worker = spec.worker_file
            server.fn_category = {f.name: f.category for f in spec.functions if f.category}
            server.categories = spec.categories()
            if spec.source_env:
                server.env = f"`{spec.source_env}`"
            else:
                name = _interpreter_env(spec.override_vars)
                server.env = f"`{name}` (no build)" if name else "(no build)"
        else:
            server.portal = _config_portal(entry)
            server.worker = _config_worker(entry)
            name = _interpreter_env(entry.get("env") or {})
            server.env = f"`{name}`" if name else ""
        servers[key] = server

        if spec is None:
            drift.append(f"`{key}`: in the canonical config, but has no spec in `{SPECS_REL}/`.")
            continue
        if entry is None:
            drift.append(f"`{key}`: has a spec, but no entry in the canonical config, so the agent never wires it.")
            continue
        spec_functions = [f.name for f in spec.functions]
        for name in spec_functions:
            if name not in server.functions:
                drift.append(f"`{key}`: function `{name}` is in the spec, but not in the canonical config.")
        for name in server.functions:
            if name not in spec_functions:
                drift.append(f"`{key}`: function `{name}` is in the canonical config, but not in the spec.")
        config_portal = _config_portal(entry)
        if spec.server_file and config_portal and config_portal != spec.server_file:
            drift.append(f"`{key}`: the spec names portal `{spec.server_file}`, the config launches `{config_portal}`.")
        config_worker = _config_worker(entry, spec.worker_var)
        if spec.worker_file and config_worker and config_worker != spec.worker_file:
            drift.append(f"`{key}`: the spec names worker `{spec.worker_file}`, the config sets `{config_worker}`.")

    for server in servers.values():
        if server.portal and server.portal not in portals_on_disk:
            drift.append(f"`{server.key}`: its portal file is not in `{TOOLS_REL}/`.")

    named = {s.portal for s in servers.values()} | {_config_portal(e) for e in config.values()}
    unwired = [p for p in portals_on_disk if p not in named]
    spec_env = {key: spec.source_env for key, spec in specs.items() if spec.source_env}
    return Catalog(servers=servers, unwired_portals=unwired, drift=drift, spec_env=spec_env)


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def _category_order(catalog: Catalog) -> list[str]:
    """The installer's skill vocabulary in menu order, then any other category, then the uncategorised."""
    seen = {s.primary for s in catalog.servers.values()}
    for server in catalog.servers.values():
        seen |= {server.fn_category.get(f, UNCATEGORISED) for f in server.functions}
    known = list(CATEGORY_ALIASES)
    extra = sorted(c for c in seen if c not in known and c != UNCATEGORISED)
    tail = [UNCATEGORISED] if UNCATEGORISED in seen else []
    return known + extra + tail


def _code(names) -> str:
    return ", ".join(f"`{n}`" for n in names)


def _function_cell(server: Server, section: str) -> str:
    cells = []
    for name in server.functions:
        category = server.fn_category.get(name, "")
        cells.append(f"`{name}`" + (f" ({category})" if category and category != section else ""))
    return ", ".join(cells) or "—"


def _row(cells) -> str:
    return "| " + " | ".join(cells) + " |"


def render_catalog(catalog: Catalog) -> str:
    servers = sorted(catalog.servers.values(), key=lambda s: s.key)
    order = _category_order(catalog)
    lines = [
        HEADER,
        "",
        "# Tool catalogue",
        "",
        f"**What this is:** every MCP portal in `{TOOLS_REL}/`, grouped by analysis category, with its worker, "
        "conda env, functions and a one-line description.",
        "",
        f"**How runtime finds it:** it does not. The agent wires portals from `{CONFIG_REL}`; this page is for readers.",
        "",
        f"**What must not change:** do not edit it by hand. It is generated from `{SPECS_REL}/*.yaml` and the "
        f"canonical config, and `{CHECK_COMMAND}` exits 1 when it is stale.",
        "",
        "Regenerate it after changing a spec, the canonical config or the portal files:",
        "",
        "```bash",
        GENERATE_COMMAND,
        "```",
        "",
        "A server is listed once, under the category of its first function; a function from another category "
        "carries that category in brackets. Env is the conda env the server's spec builds from, and *(no build)* "
        "marks a server that runs in an interpreter that already exists. The flat layout of the directory, its "
        "shared helpers and how to add a portal are in [README.md](README.md).",
        "",
        "## Categories",
        "",
        _row(["Category", "Servers", "Functions", "Also served by"]),
        _row(["---", "---:", "---:", "---"]),
    ]
    for category in order:
        primary = [s for s in servers if s.primary == category]
        functions = sum(1 for s in servers for f in s.functions if s.fn_category.get(f, UNCATEGORISED) == category)
        also = [s.key for s in servers if s.primary != category and category in s.fn_category.values()]
        label = f"[{category}](#{category})" if primary else category
        lines.append(_row([label, str(len(primary)), str(functions), _code(also) or "—"]))

    for category in order:
        primary = [s for s in servers if s.primary == category]
        if not primary:
            continue
        lines += [
            "",
            f"## {category}",
            "",
            _row(["Server", "Portal", "Worker", "Env", "Functions", "What it does"]),
            _row(["---"] * 6),
        ]
        for s in primary:
            key = f"`{s.key}`" + ("" if s.enabled else " (disabled)")
            lines.append(
                _row(
                    [
                        key,
                        f"`{s.portal}`" if s.portal else "—",
                        f"`{s.worker}`" if s.worker else "—",
                        s.env or "—",
                        _function_cell(s, category),
                        s.description or "—",
                    ]
                )
            )

    lines += ["", "## Notes"]

    renamed = [
        s for s in servers if s.portal and s.portal.endswith(PORTAL_SUFFIX) and s.portal[: -len(PORTAL_SUFFIX)] != s.key
    ]
    if renamed:
        lines += [
            "",
            "### Server keys that differ from the file names",
            "",
            "The key names the server in the config and the spec; its files keep the stem.",
            "",
            _row(["Server key", "File stem"]),
            _row(["---", "---"]),
        ]
        lines += [_row([f"`{s.key}`", f"`{s.portal[: -len(PORTAL_SUFFIX)]}_*`"]) for s in renamed]

    multi = [s for s in servers if len(s.categories) > 1]
    if multi:
        lines += [
            "",
            "### Servers in more than one category",
            "",
            _row(["Server", "Listed under", "Also"]),
            _row(["---", "---", "---"]),
        ]
        lines += [_row([f"`{s.key}`", s.primary, ", ".join(s.categories[1:])]) for s in multi]

    by_worker: dict[str, list[str]] = {}
    for s in servers:
        if s.worker:
            by_worker.setdefault(s.worker, []).append(s.key)
    shared_workers = {w: keys for w, keys in sorted(by_worker.items()) if len(keys) > 1}
    if shared_workers:
        lines += [
            "",
            "### Workers shared by more than one server",
            "",
            _row(["Worker", "Servers"]),
            _row(["---", "---"]),
        ]
        lines += [_row([f"`{w}`", _code(keys)]) for w, keys in shared_workers.items()]

    by_env: dict[str, list[str]] = {}
    for key, env in sorted(catalog.spec_env.items()):
        by_env.setdefault(env, []).append(key)
    shared_envs = {e: keys for e, keys in sorted(by_env.items()) if len(keys) > 1}
    if shared_envs:
        lines += [
            "",
            "### Conda envs shared by more than one server",
            "",
            _row(["Env", "Servers"]),
            _row(["---", "---"]),
        ]
        lines += [_row([f"`{e}`", _code(keys)]) for e, keys in shared_envs.items()]

    if catalog.unwired_portals:
        lines += [
            "",
            "### Portal files nothing wires",
            "",
            f"No spec in `{SPECS_REL}/` and no entry in the canonical config names these files, so nothing launches them.",
            "",
        ]
        lines += [f"- `{p}`" for p in catalog.unwired_portals]

    lines += ["", "### Where the specs and the canonical config disagree", ""]
    if catalog.drift:
        lines += [f"- {line}" for line in catalog.drift]
    else:
        lines.append("Nowhere: every spec matches its entry in the canonical config.")
    return "\n".join(lines) + "\n"


def render(root: Path | str) -> str:
    """The catalogue text for the checkout at ``root``."""
    return render_catalog(read_catalog(Path(root)))


def catalog_path(root: Path | str) -> Path:
    return constants.tools_dir(Path(root)) / "CATALOG.md"


# --------------------------------------------------------------------------- #
# Command line
# --------------------------------------------------------------------------- #
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m sog_install.tools_catalog",
        description=f"Print, write or check {CATALOG_REL}, the category view of the MCP portals.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help=f"rewrite {CATALOG_REL}")
    mode.add_argument("--check", action="store_true", help=f"exit 1 when {CATALOG_REL} differs from the output")
    parser.add_argument("--root", type=Path, default=None, help="checkout root (default: this checkout)")
    args = parser.parse_args(argv)

    root = args.root if args.root is not None else constants.repo_root()
    text = render(root)
    target = catalog_path(root)
    if args.write:
        target.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {CATALOG_REL}")
        return 0
    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current != text:
            state = "is missing" if current is None else "is stale"
            print(f"{CATALOG_REL} {state}; run: {GENERATE_COMMAND}", file=sys.stderr)
            return 1
        print(f"{CATALOG_REL} is up to date")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
